package com.example.crud.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.http.HttpStatus;
//import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

//import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.PathVariable;
import java.util.List;
//import java.util.Optional;
import java.util.Optional;

import javax.validation.Valid;

import com.example.crud.model.User;
import com.example.crud.repository.UserRepository;

@CrossOrigin
@RestController // This means that this class is a RestController
@RequestMapping("/user") // This means URL's start with /user (after Application path)
public class MainController {
  @Autowired // This means to get the bean called userRepository
  // Which is auto-generated by Spring, we will use it to handle the data
  private UserRepository userRepository;

  @PostMapping("/add")
  // Map ONLY POST Requests
  public ResponseEntity<String> addNewUser(@Valid User user) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request
    try {
      userRepository.save(user);
    } catch (Exception e) {
      System.out.println(e.getMessage());
    }

    return new ResponseEntity<String>("Cadastrado com sucesso", HttpStatus.OK);
  }

  @GetMapping("/add")

  public String formularioCadastrar() {
    return "cadastrar";
  }

  @GetMapping("/edit")

  public String edit() {
    return "redirect:/pessoas/listar";
  }

  @GetMapping("/ver/{id}")

  public Optional<User> ver(@PathVariable Integer id) {
    return userRepository.findById(id);
  }

  @PutMapping("/edit/{id}")

  public ResponseEntity<?> atualizar(Integer id, String email, String name) {

    return userRepository.findById(id)
              .map(record -> {
                record.setEmail(email);
                record.setName(name);
                userRepository.save(record);
                return new ResponseEntity<String>("Registro atualizado com sucesso", HttpStatus.OK);
              })
              .orElse(ResponseEntity.notFound().build());
  }

  @DeleteMapping("/delete/{id}")

  ResponseEntity<?> deletar(@PathVariable Integer id) {
    return userRepository.findById(id)
           .map(record -> {
               userRepository.deleteById(id);
               return new ResponseEntity<String>("Registro deletado com sucesso", HttpStatus.OK);
           }).orElse(ResponseEntity.notFound().build());
    
  }
  
  @GetMapping("/listar")
  public Page<User> getAllUsers(Integer pagina, Integer limite, String name) {
    
    int paginacao = 0;
    int limiteRegistros = 5;
    
    if(pagina != null) {
      paginacao = pagina;
    }

    if(limite != null) {
      limiteRegistros = limite;
    }
    
    Pageable paginador = PageRequest.of(paginacao, limiteRegistros);

    if (name != null) {
      paginador = PageRequest.of(0, 5);
      return userRepository.findByNameContainingOrderByNameAsc(name, paginador);
    }
    // This returns a JSON or XML with the users
    return userRepository.findAllByOrderByNameAsc(paginador);
  }

  /*@PostMapping(path="/buscarPorNome")
  public Page<User> getUserByName(String name) {
    // This returns a JSON or XML with the users
    if(name.length() == 0){
      return userRepository.findAllByOrderByNameAsc(null);
    }
    
    return userRepository.findByNameContainingOrderByNameAsc(name, null);
  }*/
    
}
